/**
 * @file maze.h
 * @authors
 * Group 5 
* 
* Shubham Sonawane shubhams@umd.edu \n
* Sanket Goyal sanket193@gmail.com \n
* Dipam Patel dipu18@umd.edu \n
* Kartik Venkat kartik.venkat86@gmail.com \n
* Arjun Srinivasan arjunsrinivasan.a@gmail.com \n 
* Kulbir Singh Ahluwalia kulbir@umd.edu \n
* @version 3.0
*
* @section LICENSE
*
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License as
* published by the Free Software Foundation; either version 2 of
* the License, or (at your option) any later version.
*
* @section DESCRIPTION
* 
* This class is used to read the maze generated by the micromouse simulator.
*                                                                                               
* 
*/
#pragma once
#include <array>
#include <iostream>
#include "../API/api.h"

namespace fp
{
	class Maze
	{
		private:
			 
			/**
			* @brief 2D array of size 16*16 to store the North wall
			* @param none
			* @return none
			*/
			std::array<std::array<int, 16>, 16> NorthWall;
			/**
			* @brief 2D array of size 16*16 to store the East wall
			* @param none
			* @return none
			*/
			std::array<std::array<int, 16>, 16> EastWall;
			/**
			* @brief 2D array of size 16*16 to store the South wall
			* @param none
			* @return none
			*/
			std::array<std::array<int, 16>, 16> SouthWall;
			/**
			* @brief 2D array of size 16*16 to store the West wall
			* @param none
			* @return none
			*/
			std::array<std::array<int, 16>, 16> WestWall;
				
		public:
			/**
			* @brief This constructor is used to initialize all the walls to zero.
			* @param none
			* @return none
			*/
			Maze();
			
			
			/**
			* @brief A fuction belonging to the maze class. This function is used to update the 
			* newly discovered walls
			* @param x coordinate of the wall
			* @param y-coordinate of the wall
			* @param Direction of the wall.
			* @return none
			*/
			void UpdateWall(int, int, char); 
			
			
			/**
			* @brief A fuction belonging to the maze class. This function is used to read the north wall.
			* @param x coordinate of the wall
			* @param y-coordinate of the wall
			* @return none
			*/
			int ReadWallNorth(int, int); 
			
			/**
			* @brief A fuction belonging to the maze class. This function is used to read the East wall.
			* @param x coordinate of the wall
			* @param y-coordinate of the wall
			* @return none
			*/
			int ReadWallEast(int, int);
			
			/**
			* @brief A fuction belonging to the maze class. This function is used to read the West wall.
			* @param x coordinate of the wall
			* @param y-coordinate of the wall
			* @return none
			*/
			int ReadWallWest(int, int);
		
			/**
			* @brief A fuction belonging to the maze class. This function is used to read the South wall.
			* @param x coordinate of the wall
			* @param y-coordinate of the wall
			* @return none
			*/
			int ReadWallSouth(int, int);
			/**
			* @brief It is a destructor of class Maze
			* that destroys the object created.
			* @param none
			* @return none
			*/
			~Maze() {}

	};

}

